<!DOCTYPE html>
<html>
<head>
<title>Terms of use - Edexlive</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="layout/styles/layout.css" rel="stylesheet" type="text/css" media="all">
<link href="https://fonts.googleapis.com/css?family=Archivo+Narrow|PT+Sans+Narrow" rel="stylesheet">
<link rel="shortcut icon" href="http://images.edexlive.com/images/FrontEnd/images/favicon.ico" type="image/x-icon" />
</head>
<body id="top">
<?php include('header.php'); ?>
<div id="dynamictab" class="wrapper bgded edex-bg hoc ">
  <div class="split clear">
    <section style="width:100%;background-color:transparent;"> 
	<h1><span style="font-size:25px;">Terms Of Use</span></h1>
		<div class="privacy-policy">
		<p>Express Network Private Limited (ENPL) is a sister concern of Express Publications (Madurai) Limited which publishes well known newspapers like The New Indian Express, The New Sunday Express, Dinamani, Kannada Prabha and magazines like Malayalam Vaarika, Cinema Express etc. ENPL has been granted licence by EPML to host the content generated by its various publications on the following websites:</p>
		<ul>
		<li><i class="fa fa-angle-right"></i> NEW INDIAN EXPRESS</li>
		<li><i class="fa fa-angle-right"></i> DINAMANI</li>
		<li><i class="fa fa-angle-right"></i> KANNADA PRABHA</li>
		<li><i class="fa fa-angle-right"></i> SAMAKALIKA MALAYALAM</li>
		<li><i class="fa fa-angle-right"></i> MALAYALAM VAARIKA</li>
		<li><i class="fa fa-angle-right"></i> INDULGEXPRESS</li>
		</ul>
		<p>ENPL respects the privacy of its users and is committed to protect it in all respects.</p>
		<p>With a view to offer an enriching and holistic Internet experience to its users, ENPL offers a vast repository of Online Sites and variety of community services. You may read ‘About Us’ to know more about ENPL. Most of the Online Community Services are offered for free but you need registration to surf the content stored in archives and the paid sections.</p>
		<p>Among the information that you are required to provide is: a) your name, b) email address, c) sex, d) age, e) PIN code etc., your occupation, interests, and the like. (All required information is Service Dependent). The Information as supplied by the users enables us to improve our sites and provide you a more user-friendly experience.</p>
		<p>Our web servers automatically collect limited information about your computer’s connection to the Internet, including your IP address, when you visit our sites. (The IP address is a number that lets computers attached to the Internet know where to send data — such as the web pages you view.) The IP address, however, does not identify you personally. We use this information to deliver our web pages to you upon request, to tailor our site to the interests of our users, to measure traffic within our site and let advertisers know the geographic locations from where our visitors come.</p>
		<p>ENPL includes links to other websites. Such sites are governed by their respective privacy policies, which are beyond our control. Once you leave our servers (you can tell where you are by checking the URL in the location bar on your browser), use of any information you provide is governed by the privacy policy of the operator of the site you are visiting. That policy may differ from ours. You are requested to go through the Privacy Policy of those websites before using the same. If you can’t find the privacy policy of any of these sites via a link from the site’s homepage, you should contact the site directly for more information.</p>
		<p>When we present information to our advertisers — to help them understand our audience and confirm the value of advertising on our website — it is usually in the form of aggregated statistics on traffic to various pages within our site.</p>
		<p>All information gathered on our websites is securely stored within the database controlled by us. The database is stored on servers secured behind a firewall; and access to the servers is password-protected and is strictly limited. However, as effective as our security measures are, no security system is impenetrable. We cannot guarantee the security of our database, nor can we guarantee that information you supply will not be intercepted while being transmitted to us over the Internet. And, of course, any information you include in a posting to the discussion areas is available to anyone with Internet access.</p>
		<p>* There is no cancellation.</p>
		<p>* You assume the responsibility for your registration, and no refunds will be issued.</p></div>
	  	 
</section>
  </div>
</div>


<?php include('footer.php'); ?>
<a id="backtotop" href="#top"><i class="fa fa-chevron-up"></i></a> 
<!-- JAVASCRIPTS --> 
<script src="layout/scripts/jquery.min.js"></script> 
<script src="layout/scripts/jquery.backtotop.js"></script> 
<script src="layout/scripts/jquery.mobilemenu.js"></script>
<script type="text/javascript">
	$('html,body').animate({
		scrollTop: $('#dynamictab').offset().top
	}, 1000);
</script>
</body>
</html>